SECTOR_MAP = {
    # --- Technology (Software, Hardware, Semiconductors, Cloud) ---
    "AAPL": "Technology",
    "MSFT": "Technology",
    "GOOGL": "Technology",
    "GOOG": "Technology",
    "META": "Technology",
    "NVDA": "Technology",
    "AMD": "Technology",
    "INTC": "Technology",
    "AVGO": "Technology",
    "CRM": "Technology",
    "QCOM": "Technology",
    "ADBE": "Technology",
    "ORCL": "Technology",
    "CSCO": "Technology",
    "IBM": "Technology",
    "NOW": "Technology",
    "SNPS": "Technology",
    "CDNS": "Technology",
    "ANET": "Technology",
    "NET": "Technology",
    "SNOW": "Technology",
    "MU": "Technology",
    "TXN": "Technology",
    "AMAT": "Technology",
    "LRCX": "Technology",
    "KLAC": "Technology",
    "ASML": "Technology",
    "SHOP": "Technology",
    "CRWD": "Technology",
    "PANW": "Technology",
    "FTNT": "Technology",
    "ZS": "Technology",
    "TEAM": "Technology",
    "MDB": "Technology",
    "DDOG": "Technology",
    # --- Financials (Banks, Insurance, Capital Markets, Fintech) ---
    "JPM": "Financials",
    "BAC": "Financials",
    "WFC": "Financials",
    "C": "Financials",
    "GS": "Financials",
    "MS": "Financials",
    "V": "Financials",
    "MA": "Financials",
    "PYPL": "Financials",
    "AXP": "Financials",
    "BLK": "Financials",
    "SCHW": "Financials",
    "SPGI": "Financials",
    "MCO": "Financials",
    "ICE": "Financials",
    "CME": "Financials",
    "CB": "Financials",
    "USB": "Financials",
    "PNC": "Financials",
    "TFC": "Financials",
    "BRK.B": "Financials",
    "MET": "Financials",
    "PRU": "Financials",
    "AIG": "Financials",
    "AJG": "Financials",
    "MMC": "Financials",
    "COIN": "Financials",  # Crypto exchange
    "SOFI": "Financials",
    "SQ": "Financials",  # Could also be Tech
    # --- Energy (Oil, Gas, Equipment, Renewables) ---
    "XOM": "Energy",
    "CVX": "Energy",
    "COP": "Energy",
    "SLB": "Energy",
    "EOG": "Energy",
    "MPC": "Energy",
    "PSX": "Energy",
    "VLO": "Energy",
    "OXY": "Energy",
    "KMI": "Energy",
    "WMB": "Energy",
    "HAL": "Energy",
    "BKR": "Energy",
    "EQT": "Energy",
    "PXD": "Energy",
    "DVN": "Energy",
    "FANG": "Energy",
    "ET": "Energy",
    "EPD": "Energy",
    "NEP": "Energy",  # Renewables
    # --- Healthcare (Pharma, Biotech, Devices, Managed Care) ---
    "JNJ": "Healthcare",
    "UNH": "Healthcare",
    "PFE": "Healthcare",
    "ABBV": "Healthcare",
    "LLY": "Healthcare",
    "MRK": "Healthcare",
    "TMO": "Healthcare",
    "ABT": "Healthcare",
    "BMY": "Healthcare",
    "AMGN": "Healthcare",
    "GILD": "Healthcare",
    "CVS": "Healthcare",
    "CI": "Healthcare",
    "HUM": "Healthcare",
    "MDT": "Healthcare",
    "SYK": "Healthcare",
    "BDX": "Healthcare",
    "BSX": "Healthcare",
    "ISRG": "Healthcare",
    "VRTX": "Healthcare",
    "REGN": "Healthcare",
    "BIIB": "Healthcare",
    "MRNA": "Healthcare",
    "DXCM": "Healthcare",
    "ILMN": "Healthcare",
    "ZTS": "Healthcare",
    "EW": "Healthcare",
    # --- Consumer Staples (Food, Beverage, Household, Personal Products) ---
    "KO": "Consumer Staples",
    "PEP": "Consumer Staples",
    "WMT": "Consumer Staples",
    "PG": "Consumer Staples",
    "COST": "Consumer Staples",
    "EL": "Consumer Staples",
    "CL": "Consumer Staples",
    "MO": "Consumer Staples",
    "PM": "Consumer Staples",
    "MDLZ": "Consumer Staples",
    "KHC": "Consumer Staples",
    "GIS": "Consumer Staples",
    "SYY": "Consumer Staples",
    "KMB": "Consumer Staples",
    "HSY": "Consumer Staples",
    "ADM": "Consumer Staples",
    "BF.B": "Consumer Staples",
    "STZ": "Consumer Staples",
    "KR": "Consumer Staples",
    # --- Consumer Discretionary (Retail, Auto, Hotels, Leisure) ---
    "AMZN": "Consumer Discretionary",
    "TSLA": "Consumer Discretionary",  # Often categorized here or Tech
    "HD": "Consumer Discretionary",
    "MCD": "Consumer Discretionary",
    "NKE": "Consumer Discretionary",
    "SBUX": "Consumer Discretionary",
    "LOW": "Consumer Discretionary",
    "BKNG": "Consumer Discretionary",
    "MAR": "Consumer Discretionary",
    "HLT": "Consumer Discretionary",
    "YUM": "Consumer Discretionary",
    "CMG": "Consumer Discretionary",
    "TGT": "Consumer Discretionary",  # Sometimes Staples
    "TJX": "Consumer Discretionary",
    "ROST": "Consumer Discretionary",
    "DLTR": "Consumer Discretionary",
    "F": "Consumer Discretionary",
    "GM": "Consumer Discretionary",
    "NIO": "Consumer Discretionary",
    "RIVN": "Consumer Discretionary",
    "LCID": "Consumer Discretionary",
    "BBY": "Consumer Discretionary",
    "ETSY": "Consumer Discretionary",
    "EXPE": "Consumer Discretionary",
    "CCL": "Consumer Discretionary",
    "RCL": "Consumer Discretionary",
    # --- Communications (Media, Telecom, Entertainment) ---
    "DIS": "Communications",
    "NFLX": "Communications",
    "TMUS": "Communications",
    "VZ": "Communications",
    "T": "Communications",
    "CMCSA": "Communications",
    "CHTR": "Communications",
    "EA": "Communications",
    "ATVI": "Communications",
    "TTWO": "Communications",
    "SPOT": "Communications",
    "LYV": "Communications",
    "OMC": "Communications",
    "IPG": "Communications",
    # --- Industrials (Aerospace, Defense, Machinery, Logistics) ---
    "BA": "Industrials",
    "GE": "Industrials",
    "HON": "Industrials",
    "CAT": "Industrials",
    "UPS": "Industrials",
    "FDX": "Industrials",
    "RTX": "Industrials",
    "LMT": "Industrials",
    "NOC": "Industrials",
    "GD": "Industrials",
    "DE": "Industrials",
    "EMR": "Industrials",
    "ITW": "Industrials",
    "WM": "Industrials",
    "RSG": "Industrials",
    "CSX": "Industrials",
    "UNP": "Industrials",
    "NSC": "Industrials",
    "DAL": "Industrials",
    "UAL": "Industrials",
    "LUV": "Industrials",
    "AAL": "Industrials",
    "JCI": "Industrials",
    "ETN": "Industrials",
    "ROK": "Industrials",
    "FTV": "Industrials",
    "TDG": "Industrials",
    # --- Utilities (Electric, Gas, Water, Renewable) ---
    "NEE": "Utilities",
    "DUK": "Utilities",
    "SO": "Utilities",
    "AEP": "Utilities",
    "D": "Utilities",
    "EXC": "Utilities",
    "SRE": "Utilities",
    "XEL": "Utilities",
    "WEC": "Utilities",
    "ES": "Utilities",
    "PEG": "Utilities",
    "ED": "Utilities",
    "FE": "Utilities",
    "AES": "Utilities",
    "AWK": "Utilities",
    # --- Real Estate (REITs: Office, Retail, Residential, Industrial, Towers) ---
    "PLD": "Real Estate",
    "AMT": "Real Estate",
    "EQIX": "Real Estate",
    "PSA": "Real Estate",
    "CCI": "Real Estate",
    "DLR": "Real Estate",
    "O": "Real Estate",
    "SPG": "Real Estate",
    "AVB": "Real Estate",
    "EQR": "Real Estate",
    "WELL": "Real Estate",
    "VTR": "Real Estate",
    "SBAC": "Real Estate",
    "WY": "Real Estate",
    "BXP": "Real Estate",
    "VNO": "Real Estate",
    "IRM": "Real Estate",
    "ARE": "Real Estate",
    # --- Materials (Chemicals, Metals, Mining, Construction) ---
    "LIN": "Materials",
    "APD": "Materials",
    "SHW": "Materials",
    "ECL": "Materials",
    "NEM": "Materials",
    "FCX": "Materials",
    "SCCO": "Materials",
    "VMC": "Materials",
    "MLM": "Materials",
    "STLD": "Materials",
    "NUE": "Materials",
    "CTVA": "Materials",
    "DD": "Materials",
    "DOW": "Materials",
    "LYB": "Materials",
    "PKG": "Materials",
    "WRK": "Materials",
    "CF": "Materials",
    "MOS": "Materials",
    # --- Popular ETFs (for sector tracking or general market) ---
    "SPY": "ETF",
    "IVV": "ETF",
    "VOO": "ETF",
    "QQQ": "ETF",
    "VTI": "ETF",
    "DIA": "ETF",
    "IWM": "ETF",
    "XLK": "ETF",
    "XLF": "ETF",
    "XLV": "ETF",
    "XLE": "ETF",
    "XLY": "ETF",
    "XLP": "ETF",
    "XLI": "ETF",
    "XLC": "ETF",
    "XLU": "ETF",
    "XLRE": "ETF",
    "XLB": "ETF",
    "ARKK": "ETF",
    "VGT": "ETF",
    "VHT": "ETF",
    "VDC": "ETF",
    "VNQ": "ETF",
}

pairs = [
    {
        "asset_1": "AAPL",
        "asset_2": "MSFT",
        "sector": "Technology",
        "correlation": 0.85,
        "cointegration_pvalue": 0.01,
        "description": "Tech Giants - highly correlated",
    },
    {
        "asset_1": "GOOGL",
        "asset_2": "META",
        "sector": "Technology",
        "correlation": 0.78,
        "cointegration_pvalue": 0.02,
        "description": "Ad-driven tech companies",
    },
    {"asset_1": "JPM", "asset_2": "BAC", "sector": "Financials", "correlation": 0.91, "cointegration_pvalue": 0.005, "description": "Major US banks"},
    {
        "asset_1": "KO",
        "asset_2": "PEP",
        "sector": "Consumer Staples",
        "correlation": 0.82,
        "cointegration_pvalue": 0.015,
        "description": "Beverage companies",
    },
    {"asset_1": "XOM", "asset_2": "CVX", "sector": "Energy", "correlation": 0.89, "cointegration_pvalue": 0.008, "description": "Oil & gas majors"},
    {
        "asset_1": "NVDA",
        "asset_2": "AMD",
        "sector": "Technology",
        "correlation": 0.76,
        "cointegration_pvalue": 0.03,
        "description": "GPU/semiconductor manufacturers",
    },
]
