"""initial schema

Revision ID: 5ebb4254851c
Revises: 
Create Date: 2026-03-03 13:37:54.997098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ebb4254851c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('macro_cache',
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('data_size', sa.Integer(), nullable=False),
    sa.Column('compression', sa.String(length=10), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('cache_key')
    )
    op.create_index(op.f('ix_macro_cache_cache_key'), 'macro_cache', ['cache_key'], unique=False)
    op.create_index('ix_macro_cache_created', 'macro_cache', ['created_at'], unique=False)
    op.create_index('ix_macro_cache_expires', 'macro_cache', ['expires_at'], unique=False)
    op.create_index(op.f('ix_macro_cache_expires_at'), 'macro_cache', ['expires_at'], unique=False)
    op.create_table('market_data_cache',
    sa.Column('cache_key', sa.String(), nullable=False),
    sa.Column('data_type', sa.String(), nullable=False),
    sa.Column('data_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('expires_at', sa.Float(), nullable=False),
    sa.Column('access_count', sa.Integer(), nullable=True),
    sa.Column('last_accessed', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('cache_key')
    )
    op.create_index('idx_market_cache_expires_at', 'market_data_cache', ['expires_at'], unique=False)
    op.create_index(op.f('ix_market_data_cache_expires_at'), 'market_data_cache', ['expires_at'], unique=False)
    op.create_table('options_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('strategy', sa.String(length=100), nullable=True),
    sa.Column('entry_date', sa.DateTime(), nullable=True),
    sa.Column('expiration', sa.DateTime(), nullable=True),
    sa.Column('initial_cost', sa.Numeric(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('pnl', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_options_positions_id'), 'options_positions', ['id'], unique=False)
    op.create_table('rate_limits',
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('remaining', sa.Integer(), nullable=False),
    sa.Column('reset_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('provider')
    )
    op.create_index(op.f('ix_rate_limits_provider'), 'rate_limits', ['provider'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_id'), 'activities', ['id'], unique=False)
    op.create_table('backtest_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('backtest_type', sa.String(), nullable=False),
    sa.Column('symbols', sa.JSON(), nullable=False),
    sa.Column('strategy_config', sa.JSON(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('interval', sa.String(), nullable=False),
    sa.Column('initial_capital', sa.Float(), nullable=False),
    sa.Column('total_return', sa.Float(), nullable=True),
    sa.Column('total_return_pct', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('final_equity', sa.Float(), nullable=True),
    sa.Column('equity_curve', sa.JSON(), nullable=True),
    sa.Column('trades_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('celery_task_id', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_runs_celery_task_id'), 'backtest_runs', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_backtest_runs_id'), 'backtest_runs', ['id'], unique=False)
    op.create_table('bubble_detection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('detected', sa.Boolean(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('crash_probability', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bubble_detection_id'), 'bubble_detection', ['id'], unique=False)
    op.create_index(op.f('ix_bubble_detection_symbol'), 'bubble_detection', ['symbol'], unique=False)
    op.create_index(op.f('ix_bubble_detection_user_id'), 'bubble_detection', ['user_id'], unique=False)
    op.create_table('crash_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('crash_probability', sa.Float(), nullable=False),
    sa.Column('intensity', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('lppls_confidence', sa.Float(), nullable=True),
    sa.Column('lppls_crash_probability', sa.Float(), nullable=True),
    sa.Column('lppls_bubble_detected', sa.Boolean(), nullable=True),
    sa.Column('lppls_critical_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lstm_stress_index', sa.Float(), nullable=True),
    sa.Column('lstm_confidence', sa.Float(), nullable=True),
    sa.Column('lstm_stress_trend', sa.String(length=20), nullable=True),
    sa.Column('rf_ensemble_probability', sa.Float(), nullable=True),
    sa.Column('combined_score', sa.Float(), nullable=True),
    sa.Column('hedge_strategy', sa.String(length=50), nullable=True),
    sa.Column('hedge_cost', sa.Float(), nullable=True),
    sa.Column('hedge_coverage', sa.Float(), nullable=True),
    sa.Column('hedge_details', sa.JSON(), nullable=True),
    sa.Column('alert_sent', sa.Boolean(), nullable=True),
    sa.Column('alert_level', sa.String(length=20), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crash_predictions_id'), 'crash_predictions', ['id'], unique=False)
    op.create_index(op.f('ix_crash_predictions_symbol'), 'crash_predictions', ['symbol'], unique=False)
    op.create_index(op.f('ix_crash_predictions_timestamp'), 'crash_predictions', ['timestamp'], unique=False)
    op.create_index(op.f('ix_crash_predictions_user_id'), 'crash_predictions', ['user_id'], unique=False)
    op.create_table('hedge_execution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('strategy', sa.String(length=100), nullable=True),
    sa.Column('crash_probability', sa.Numeric(), nullable=True),
    sa.Column('confidence', sa.Numeric(), nullable=True),
    sa.Column('cost', sa.Numeric(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hedge_execution_id'), 'hedge_execution', ['id'], unique=False)
    op.create_index(op.f('ix_hedge_execution_user_id'), 'hedge_execution', ['user_id'], unique=False)
    op.create_table('marketplace_strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('creator_name', sa.String(), nullable=False),
    sa.Column('strategy_type', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('complexity', sa.String(), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('total_return', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('num_trades', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verification_badge', sa.Text(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pros', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('recommended_capital', sa.Float(), nullable=True),
    sa.Column('downloads', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('num_ratings', sa.Integer(), nullable=True),
    sa.Column('num_reviews', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_strategies_id'), 'marketplace_strategies', ['id'], unique=False)
    op.create_table('options_legs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('option_type', sa.String(length=10), nullable=True),
    sa.Column('strike', sa.Numeric(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('premium', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['options_positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_options_legs_id'), 'options_legs', ['id'], unique=False)
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('initial_capital', sa.Float(), nullable=False),
    sa.Column('current_capital', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_id'), 'portfolios', ['id'], unique=False)
    op.create_table('strategy_marketplace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('strategy_key', sa.String(length=100), nullable=False),
    sa.Column('default_parameters', sa.JSON(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('creator_name', sa.String(length=255), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('avg_return_pct', sa.Float(), nullable=True),
    sa.Column('avg_sharpe', sa.Float(), nullable=True),
    sa.Column('avg_win_rate', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('total_deployments', sa.Integer(), nullable=True),
    sa.Column('price_monthly', sa.Float(), nullable=True),
    sa.Column('has_free_trial', sa.Boolean(), nullable=True),
    sa.Column('trial_days', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('num_ratings', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_marketplace_id'), 'strategy_marketplace', ['id'], unique=False)
    op.create_table('usage_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_tracking_action'), 'usage_tracking', ['action'], unique=False)
    op.create_index(op.f('ix_usage_tracking_id'), 'usage_tracking', ['id'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.Column('slippage', sa.Float(), nullable=True),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('initial_capital', sa.Float(), nullable=True),
    sa.Column('live_data_source', sa.String(), nullable=True),
    sa.Column('default_broker', sa.String(), nullable=True),
    sa.Column('auto_connect_broker', sa.Boolean(), nullable=True),
    sa.Column('broker_api_key', sa.String(), nullable=True),
    sa.Column('broker_api_secret', sa.String(), nullable=True),
    sa.Column('broker_base_url', sa.String(), nullable=True),
    sa.Column('broker_host', sa.String(), nullable=True),
    sa.Column('broker_port', sa.Integer(), nullable=True),
    sa.Column('broker_client_id', sa.Integer(), nullable=True),
    sa.Column('user_ib_account_id', sa.String(), nullable=True),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('notifications', sa.Boolean(), nullable=True),
    sa.Column('auto_refresh', sa.Boolean(), nullable=True),
    sa.Column('refresh_interval', sa.Integer(), nullable=True),
    sa.Column('alert_preferences', sa.JSON(), nullable=True),
    sa.Column('crash_monitoring', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_settings_id'), 'user_settings', ['id'], unique=False)
    op.create_table('live_strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('strategy_key', sa.String(length=100), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('symbols', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('backtest_id', sa.Integer(), nullable=True),
    sa.Column('deployment_mode', sa.Enum('PAPER', 'LIVE', name='deploymentmode'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'PAUSED', 'STOPPED', 'ERROR', name='strategystatus'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('initial_capital', sa.Float(), nullable=False),
    sa.Column('current_equity', sa.Float(), nullable=True),
    sa.Column('max_position_pct', sa.Float(), nullable=True),
    sa.Column('stop_loss_pct', sa.Float(), nullable=True),
    sa.Column('daily_loss_limit', sa.Float(), nullable=True),
    sa.Column('max_drawdown_limit', sa.Float(), nullable=True),
    sa.Column('total_return', sa.Float(), nullable=True),
    sa.Column('total_return_pct', sa.Float(), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('winning_trades', sa.Integer(), nullable=True),
    sa.Column('losing_trades', sa.Integer(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('daily_pnl', sa.Float(), nullable=True),
    sa.Column('daily_trades', sa.Integer(), nullable=True),
    sa.Column('backtest_return_pct', sa.Float(), nullable=True),
    sa.Column('backtest_sharpe', sa.Float(), nullable=True),
    sa.Column('backtest_max_drawdown', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_trade_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_equity_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('broker', sa.String(length=50), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtest_runs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_strategies_id'), 'live_strategies', ['id'], unique=False)
    op.create_table('performance_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('equity', sa.Numeric(), nullable=False),
    sa.Column('cash', sa.Numeric(), nullable=False),
    sa.Column('total_return', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_performance_portfolio_timestamp', 'performance_history', ['portfolio_id', sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('ix_performance_history_id'), 'performance_history', ['id'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('unrealized_pnl', sa.Float(), nullable=True),
    sa.Column('unrealized_pnl_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_id'), 'positions', ['id'], unique=False)
    op.create_table('strategy_backtests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('backtest_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('equity_curve', sa.LargeBinary(), nullable=True),
    sa.Column('trades_history', sa.LargeBinary(), nullable=True),
    sa.Column('daily_returns', sa.LargeBinary(), nullable=True),
    sa.Column('start_date', sa.String(), nullable=True),
    sa.Column('end_date', sa.String(), nullable=True),
    sa.Column('initial_capital', sa.Float(), nullable=True),
    sa.Column('symbols', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['marketplace_strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_backtests_id'), 'strategy_backtests', ['id'], unique=False)
    op.create_table('strategy_downloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['marketplace_strategies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['marketplace_strategies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_id', 'user_id', name='_strategy_user_fav_uc')
    )
    op.create_table('strategy_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('performance_achieved', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['marketplace_strategies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_id', 'user_id', name='_strategy_user_review_uc')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('order_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('slippage', sa.Float(), nullable=True),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.Column('profit_pct', sa.Float(), nullable=True),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('side', sa.String(), nullable=True),
    sa.Column('strategy', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_id'), 'trades', ['id'], unique=False)
    op.create_table('live_equity_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('equity', sa.Float(), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('positions_value', sa.Float(), nullable=True),
    sa.Column('daily_pnl', sa.Float(), nullable=True),
    sa.Column('total_pnl', sa.Float(), nullable=True),
    sa.Column('drawdown_pct', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['live_strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_equity_snapshots_id'), 'live_equity_snapshots', ['id'], unique=False)
    op.create_table('live_strategy_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['live_strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_strategy_snapshots_id'), 'live_strategy_snapshots', ['id'], unique=False)
    op.create_table('live_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', 'SHORT', 'COVER', name='tradeside'), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('order_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'CANCELLED', name='tradestatus'), nullable=False),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.Column('profit_pct', sa.Float(), nullable=True),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('total_fees', sa.Float(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('strategy_signal', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['live_strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_trades_id'), 'live_trades', ['id'], unique=False)
    op.create_index(op.f('ix_live_trades_symbol'), 'live_trades', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_live_trades_symbol'), table_name='live_trades')
    op.drop_index(op.f('ix_live_trades_id'), table_name='live_trades')
    op.drop_table('live_trades')
    op.drop_index(op.f('ix_live_strategy_snapshots_id'), table_name='live_strategy_snapshots')
    op.drop_table('live_strategy_snapshots')
    op.drop_index(op.f('ix_live_equity_snapshots_id'), table_name='live_equity_snapshots')
    op.drop_table('live_equity_snapshots')
    op.drop_index(op.f('ix_trades_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_table('strategy_reviews')
    op.drop_table('strategy_favorites')
    op.drop_table('strategy_downloads')
    op.drop_index(op.f('ix_strategy_backtests_id'), table_name='strategy_backtests')
    op.drop_table('strategy_backtests')
    op.drop_index(op.f('ix_positions_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_performance_history_id'), table_name='performance_history')
    op.drop_index('idx_performance_portfolio_timestamp', table_name='performance_history')
    op.drop_table('performance_history')
    op.drop_index(op.f('ix_live_strategies_id'), table_name='live_strategies')
    op.drop_table('live_strategies')
    op.drop_index(op.f('ix_user_settings_id'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_usage_tracking_id'), table_name='usage_tracking')
    op.drop_index(op.f('ix_usage_tracking_action'), table_name='usage_tracking')
    op.drop_table('usage_tracking')
    op.drop_index(op.f('ix_strategy_marketplace_id'), table_name='strategy_marketplace')
    op.drop_table('strategy_marketplace')
    op.drop_index(op.f('ix_portfolios_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_options_legs_id'), table_name='options_legs')
    op.drop_table('options_legs')
    op.drop_index(op.f('ix_marketplace_strategies_id'), table_name='marketplace_strategies')
    op.drop_table('marketplace_strategies')
    op.drop_index(op.f('ix_hedge_execution_user_id'), table_name='hedge_execution')
    op.drop_index(op.f('ix_hedge_execution_id'), table_name='hedge_execution')
    op.drop_table('hedge_execution')
    op.drop_index(op.f('ix_crash_predictions_user_id'), table_name='crash_predictions')
    op.drop_index(op.f('ix_crash_predictions_timestamp'), table_name='crash_predictions')
    op.drop_index(op.f('ix_crash_predictions_symbol'), table_name='crash_predictions')
    op.drop_index(op.f('ix_crash_predictions_id'), table_name='crash_predictions')
    op.drop_table('crash_predictions')
    op.drop_index(op.f('ix_bubble_detection_user_id'), table_name='bubble_detection')
    op.drop_index(op.f('ix_bubble_detection_symbol'), table_name='bubble_detection')
    op.drop_index(op.f('ix_bubble_detection_id'), table_name='bubble_detection')
    op.drop_table('bubble_detection')
    op.drop_index(op.f('ix_backtest_runs_id'), table_name='backtest_runs')
    op.drop_index(op.f('ix_backtest_runs_celery_task_id'), table_name='backtest_runs')
    op.drop_table('backtest_runs')
    op.drop_index(op.f('ix_activities_id'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_rate_limits_provider'), table_name='rate_limits')
    op.drop_table('rate_limits')
    op.drop_index(op.f('ix_options_positions_id'), table_name='options_positions')
    op.drop_table('options_positions')
    op.drop_index(op.f('ix_market_data_cache_expires_at'), table_name='market_data_cache')
    op.drop_index('idx_market_cache_expires_at', table_name='market_data_cache')
    op.drop_table('market_data_cache')
    op.drop_index(op.f('ix_macro_cache_expires_at'), table_name='macro_cache')
    op.drop_index('ix_macro_cache_expires', table_name='macro_cache')
    op.drop_index('ix_macro_cache_created', table_name='macro_cache')
    op.drop_index(op.f('ix_macro_cache_cache_key'), table_name='macro_cache')
    op.drop_table('macro_cache')
    # ### end Alembic commands ###
